# Site settings
title: "Mister Smith AI Agent Framework"
description: "Multi-agent orchestration framework built with Rust"
url: "https://mattmagg.github.io"
baseurl: "/Mister-Smith"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  core_architecture:
    output: true
    permalink: /:collection/:name/
  data_management:
    output: true
    permalink: /:collection/:name/
  operations:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/
  security:
    output: true
    permalink: /:collection/:name/
  transport:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
