name: Documentation - Security & Cryptography

on:
  workflow_dispatch:
    inputs:
      focus_area:
        description: 'Specific security area to focus on'
        required: false
        type: choice
        options:
          - 'all'
          - 'authentication'
          - 'authorization'
          - 'encryption'
          - 'security-patterns'
        default: 'all'
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  push:
    paths:
      - 'ms-framework-docs/security/*.md'

jobs:
  improve-security-docs:
    name: Improve Security Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="docs/security-improvements-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      
      - name: Improve Authentication Documentation
        if: github.event.inputs.focus_area == 'all' || github.event.inputs.focus_area == 'authentication'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-sonnet-4-20250514"
          direct_prompt: |
            You are improving the MisterSmith framework authentication documentation.
            
            CONTEXT7 LIBRARY REFERENCES:
            - jwt-simple v0.12.10 (/rafaelbarbosa/jwt-simple) - JWT handling
            - ring v0.17.8 (/briansmith/ring) - Cryptography
            
            TASK: Improve ms-framework-docs/security/authentication-implementation.md by:
            
            1. Use Context7 to get REAL jwt-simple v0.12.10 code:
               - Search for "jwt encode decode"
               - Search for "jwt claims"
               - Search for "jwt rsa ecdsa"
               - Get actual JWT implementation examples
            
            2. Take the REAL JWT code and adapt:
               - Convert actual token generation to pseudocode
               - Use real key management from examples
               - Base refresh on actual JWT patterns
               - Keep real validation logic
            
            3. Search web for actual JWT libraries and security guides
            
            4. Ensure consistency with:
               - authorization-implementation.md
               - security-framework.md
               - All transport layers (HTTP headers, gRPC metadata)
            
            5. Use REAL security patterns from production code
            
            IMPORTANT: Use Context7's actual jwt-simple examples,
            convert to pseudocode preserving real security patterns.
      
      - name: Improve Authorization Documentation
        if: github.event.inputs.focus_area == 'all' || github.event.inputs.focus_area == 'authorization'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-sonnet-4-20250514"
          direct_prompt: |
            You are improving the MisterSmith framework authorization documentation.
            
            TASK: Improve ms-framework-docs/security/authorization-implementation.md and authorization-specifications.md by:
            
            1. Find REAL authorization code:
               - Search web for actual RBAC/ABAC Rust libraries
               - Look for casbin-rs, oso, or similar
               - Find real permission checking code
            
            2. Adapt REAL authorization patterns:
               - Use actual RBAC implementations
               - Take ABAC rules from real systems
               - Base policies on actual engines
               - Keep real permission evaluation
               - Use actual audit logging code
            
            3. Define schemas from REAL systems:
               - Permission models from actual code
               - Role hierarchies from production
               - Policy syntax from real engines
               - Context from actual middleware
            
            4. Cross-reference with:
               - authentication-implementation.md
               - All agent operation files
               - Transport middleware integration
            
            IMPORTANT: Use real authorization libraries as reference,
            convert to pseudocode preserving actual patterns.
      
      - name: Improve Encryption Documentation
        if: github.event.inputs.focus_area == 'all' || github.event.inputs.focus_area == 'encryption'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-sonnet-4-20250514"
          direct_prompt: |
            You are improving the MisterSmith framework encryption documentation.
            
            CONTEXT7 LIBRARY REFERENCES:
            - ring v0.17.8 (/briansmith/ring) - Crypto primitives
            - aes-gcm v0.10.3 - AES encryption
            - chacha20poly1305 v0.10.1 - ChaCha encryption
            
            TASK: Create/improve encryption documentation by:
            
            1. Use Context7 to get REAL ring v0.17.8 code:
               - Search for "ring aead"
               - Search for "ring pbkdf2"
               - Search for "ring rand"
               - Get actual crypto examples
            
            2. If needed, create ms-framework-docs/security/encryption-patterns.md
            3. Take the REAL crypto code and adapt:
               - Convert actual AES-GCM usage to pseudocode
               - Use real KDF implementations
               - Base key rotation on actual patterns
               - Keep real random generation
               - Use actual TLS configs
            
            4. Search web for actual key management systems
            
            5. Cross-reference with:
               - All transport layers (TLS config)
               - Database encryption
               - Message encryption patterns
            
            IMPORTANT: Use Context7's actual ring examples,
            convert to safe pseudocode patterns.
      
      - name: Improve Security Patterns Documentation
        if: github.event.inputs.focus_area == 'all' || github.event.inputs.focus_area == 'security-patterns'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-sonnet-4-20250514"
          direct_prompt: |
            You are improving the MisterSmith security patterns documentation.
            
            TASK: Improve ms-framework-docs/security/security-patterns.md by:
            
            1. Find REAL security implementations:
               - Search for actual zero trust Rust code
               - Look for real validation libraries
               - Find actual rate limiting implementations
               - Get real security header configs
            
            2. Adapt REAL security code:
               - Use actual input validation patterns
               - Take CSRF protection from real frameworks
               - Base rate limiting on actual libraries
               - Keep real header configurations
               - Use actual secrets management code
            
            3. Include REAL threat mitigations:
               - Attack vectors from actual CVEs
               - Mitigations from real patches
               - Boundaries from actual architectures
               - Trust zones from production systems
            
            4. Cross-reference with:
               - security-framework.md
               - security-integration.md
               - All transport and data layers
            
            5. Create checklists from REAL security audits
            
            IMPORTANT: Use real security code as reference,
            convert to documentation preserving actual defenses.
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes made"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            git add -A
            git commit -m "docs: Improve security & cryptography documentation
            
            - Enhanced authentication with JWT patterns
            - Added comprehensive authorization models
            - Improved encryption and key management
            - Updated security patterns and threat models
            
            Based on Context7 library documentation:
            - jwt-simple v0.12.10
            - ring v0.17.8
            - aes-gcm v0.10.3
            - chacha20poly1305 v0.10.1"
          fi
      
      - name: Push changes and create PR
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git push origin "${{ env.BRANCH_NAME }}"
          gh pr create \
            --title "docs: Security & Cryptography Documentation Improvements" \
            --body "## Security Documentation Updates
            
            This PR improves the security documentation based on:
            - jwt-simple v0.12.10 (JWT authentication)
            - ring v0.17.8 (cryptographic primitives)
            - Modern security patterns and threat models
            
            ### Changes
            - Enhanced authentication flows and patterns
            - Added authorization models (RBAC/ABAC)
            - Improved encryption and key management
            - Updated security patterns and checklists
            
            ### Context7 References
            - jwt-simple: /rafaelbarbosa/jwt-simple
            - ring: /briansmith/ring
            
            ### Security Considerations
            - All examples use pseudocode only
            - No sensitive implementation details
            - Focus on patterns and best practices
            
            Generated by Security Documentation workflow" \
            --base main \
            --head "${{ env.BRANCH_NAME }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}